### ISSUE TITLE
The progress bar of the windows system shows some problems

### ISSUE THREAD

**Issue by fguby** [pterm/pterm#151] opened 2020-11-29 14:35 UTC
![image](https://user-images.githubusercontent.com/33178517/100544791-1ba03e80-3293-11eb-82c3-fe3cb701d757.png)

**Comment by fguby** [comment] 2020-11-29 14:38
My code 
```
	p, _ := pterm.DefaultProgressbar.WithTotal(len(fakeInstallList)).WithTitle("Downloading stuff").Start()

	for i := 0; i < p.Total; i++ {
		p.Title = "Downloading " + fakeInstallList[i]              // Update the title of the progressbar.
		pterm.Success.Println("Downloading " + fakeInstallList[i]) // If a progressbar is running, each print will be printed above the progressbar.
		p.Increment()                                              // Increment the progressbar by one. Use Add(x int) to increment by a custom amount.
		time.Sleep(time.Millisecond * 350)                         // Sleep 350 milliseconds.
	}
```

**Comment by MarvinJWendt** [comment] 2020-11-29 14:38
Hi, could you please tell us which OS version and Terminal you're using? 
Looks like the terminal doesn't allow carriage returns `\r` in ANSI.
BTW: Did you close this on purpose?

**Comment by fguby** [comment] 2020-11-29 14:40
I am using the windows10 operating system, I just compiled the example code to run
```
p, _ := pterm.DefaultProgressbar.WithTotal(len(fakeInstallList)).WithTitle("Downloading stuff").Start()

	for i := 0; i < p.Total; i++ {
		p.Title = "Downloading " + fakeInstallList[i]              // Update the title of the progressbar.
		pterm.Success.Println("Downloading " + fakeInstallList[i]) // If a progressbar is running, each print will be printed above the progressbar.
		p.Increment()                                              // Increment the progressbar by one. Use Add(x int) to increment by a custom amount.
		time.Sleep(time.Millisecond * 350)                         // Sleep 350 milliseconds.
	}
```

**Comment by MarvinJWendt** [comment] 2020-11-29 14:41
Are you using CMD or PowerShell?

**Comment by fguby** [comment] 2020-11-29 14:42
CMD
![image](https://user-images.githubusercontent.com/33178517/100544941-260f0800-3294-11eb-85c8-9278397c595a.png)

**Comment by MarvinJWendt** [comment] 2020-11-29 14:43
Hmm I see, this is weird, on my CMD is works just fine.
I'll look into this.

**Comment by MarvinJWendt** [comment] 2020-11-29 14:52
Hi @fguby, could you please run this snippet and post a screenshot of the outcoming (preferably one screenshot of CMD and one of PowerShell)?

```go
package main

import "fmt"

func main() {
	fmt.Print("Hello\rWorld\rOverwrite\n")

	fmt.Print("Hello")
	fmt.Print("\r")
	fmt.Print("World")
	fmt.Print("\r")
	fmt.Print("Overwrite")
	fmt.Print("\n")
}
```

**Comment by fguby** [comment] 2020-11-29 14:55
![image](https://user-images.githubusercontent.com/33178517/100545277-fe20a400-3295-11eb-9af7-7408a2c1a15d.png)

**Comment by MarvinJWendt** [comment] 2020-11-29 15:14
Could you also try this:

```go
package main

import (
	"strings"
	"time"

	"github.com/pterm/pterm"
)

// Slice of strings with placeholder text.
var fakeInstallList = strings.Split("pseudo-excel pseudo-photoshop pseudo-chrome pseudo-outlook pseudo-explorer "+
	"pseudo-dops pseudo-git pseudo-vsc pseudo-intellij pseudo-minecraft pseudo-scoop pseudo-chocolatey", " ")

func main() {
	// Create progressbar as fork from the default progressbar.
	p, _ := pterm.DefaultProgressbar.WithTotal(len(fakeInstallList)).WithTitle("Downloading stuff").Start()

	for i := 0; i < p.Total; i++ {
		p.Title = "Downloading " + fakeInstallList[i]              // Update the title of the progressbar.
		// pterm.Success.Println("Downloading " + fakeInstallList[i]) // If a progressbar is running, each print will be printed above the progressbar.
		p.Increment()                                              // Increment the progressbar by one. Use Add(x int) to increment by a custom amount.
		time.Sleep(time.Millisecond * 350)                         // Sleep 350 milliseconds.
	}
}

```

Maybe the Println in between the progressbar updates, bothers your cmd.

**Comment by fguby** [comment] 2020-11-29 15:21
I tried this, but the result is the same

**Comment by MarvinJWendt** [comment] 2020-11-29 16:45
I have tried to reproduce the problem so far, unfortunately without success. For me (and some colleagues) the example works just like it should. Maybe you could verify again that PTerm runs on the latest version (`v0.12.7`). Since I can't reproduce the problem, I'm not able to find out what the problem is at the moment. 

Do you use a Chinese Windows version? Since the codepage of CMD is different there, I could imagine that the ANSI handling is also a bit different.

Would you possibly run the example again with Powershell? 
At least the new [Windows Terminal](https://www.microsoft.com/de-de/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) should work.

If you have any further information that could help us to solve the problem, we would be very thankful.

**Comment by fguby** [comment] 2020-11-30 06:32
I tried to run the example code on another windows machine and found that the result was correct, but I encountered another problem.

After running the `go run main.go` command, I need to wait a long time.

**Comment by MarvinJWendt** [comment] 2020-12-01 11:51
What do you mean by "long time"? `go run main.go` compiles the code, and then runs it. If you run `go build` beforehand, and execute the compiled binary, does the execution still take time?

**Comment by fguby** [comment] 2020-12-01 14:47
yes,  I guess it’s a problem with my windows, thanks for your help, I will close this question.

**Closed** 2020-12-01 14:47 UTC
Labels: bug, unreproducable
